### ISSUE TITLE
Requires plugin `org.jetbrains.idea.maven` error in PyCharm

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#1468]
**Description**

UnitTestBot is not working in PyCharm.
The following error is showing: Requires plugin `org.jetbrains.idea.maven`

**To Reproduce**

1. Install PyCharm 2022.2.4
2. Download one of the latest plugin builds from main
3. File > Settings > Plugins > Install from disk > select downloaded UnitTestBot

**Expected behavior**

UnitTestBot should be installed without errors.

**Actual behavior**

The following error is showing: Requires plugin `org.jetbrains.idea.maven`

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/206133709-41f146c0-f1b0-42a0-b342-0918d0790193.png)

File > Settings > Plugins:

![image](https://user-images.githubusercontent.com/37301492/206133678-dc6e23df-f74a-47c2-8ba6-e727fc402a8f.png)

**Environment**

Windows 10 Pro
PyCharm COmmunity 2022.2.4 (not the latest, 222.* version)

**Comment by EgorkaKulikov** [comment]
Some improvements on this issue, related especially to dependency on current plugin, are fixed in the mentioned PR.

However, we still have some problems with PyCharm.
First of all, currently used ideVersion is incorrect for PyCharm: `PC-2022.2.2` should be used (see https://github.com/JetBrains/educational-plugin/blob/master/gradle-222.properties for more details).
After that, trying to use this plugin leads to the following error: find builtin plugin java for IDE
 
In future we should separate all dependent on java plugin functionality and avoid such problems.

**Comment by denis-fokin** [comment]
For now, Python and JS are in experimental mode. Let's solve the issue with dependencies in the upcoming release.

**Comment by tamarinvs19** [comment]
Fixed by PR #2611
