### ISSUE TITLE
Improve Spring integration tests minimization to minimize database content

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2219]
**Description**

Spring integration tests store some information to database before running method under tests.
However, if there are two potential test methods for one branch, we should prefer the method without database communication or with minimal database communication, because it is faster and more safe.

We should improve minimization strategy to select method with minimal database interaction if all other minimization conditions are similar for them.

**Comment by EgorkaKulikov** [comment]
We should investigate the following questions (in mentioned priority):
- do we really avoid creating database content if it is not required in this current test (even if repository is autowired and some database content is generated for tests for other methods)
- do we really avoid creating several test methods differing only in database content? (hope it is guarantied by our minimization strategy)

**Comment by IlyaMuravjov** [comment]
Right now tests like this one with non-minimized database content do generate
```java
/**
 * @utbot.classUnderTest {@link OrderService}
 * @utbot.methodUnderTest {@link OrderService#deleteOrderById(Long)}
 */
@Test
@DisplayName("deleteOrderById: id = orderRepository.save(id = orderRepository.save(id = Order())).id -> return true")
public void testDeleteOrderByIdReturnsTrue() throws ClassNotFoundException, IllegalAccessException, NoSuchFieldException, InvocationTargetException, NoSuchMethodException {
    Order order2 = new Order();
    order2.setBuyer("abc");
    orderRepository1.save(order2);
    Order order3 = new Order();
    order3.setId(-1L);
    order3.setBuyer("10");
    order3.setPrice(-1.0);
    order3.setQty(1);
    Order order4 = ((Order) orderRepository1.save(order3));
    Order order5 = ((Order) orderRepository1.save(order4));
    Long id = ((Long) getFieldValue(order5, "com.rest.order.models.Order", "id"));

    boolean actual = orderService.deleteOrderById(id);

    assertTrue(actual);
}
```

**Comment by IlyaMuravjov** [comment]
Maybe minimization of database content (and overall minimization of the test models) can be done by changing how we emit `UtFuzzedExecution`. Right now if we see a new `UtFuzzedExecution` we only emit it if it has some `Coverage` that has never been seen before (see [line `if (trieNode.count > 1) {` in `UtBotSymbolicEngine`](https://github.com/UnitTestBot/UTBotJava/blob/4d1cfc8dc34dbf3253a8c71d6d8287222c5536c2/utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt#L484C17-L484C42)).

What I suggest to try is when we have multiple `UtFuzzedExecution`s with identical `Coverage` to choose one that is likely to result in smaller test method, rather than just simply choosing the first one.
