### ISSUE TITLE
Support fuzzing mutations of autowired models

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2238]
**Description**

Currently fizzer constructs objects with constructors and modifies them, mostly by setting accessible fields.

We should be able to mutate autowired objects taking into account their specific:
- do not mutate autowired fields
- mutate other fields
- possible call some methods of the instance

This logic should be incapsulated in AutowiredValueProvider.

**Comment by IlyaMuravjov** [comment]
It's worth keeping in mind that right now when constructing new objects (from `Seed.Recursive`) fuzzer tries to use **all** available mutations, which can be problematic if we directly let it know about every public method of every relevant bean, since many of them might throw exceptions (when given random arguments), and it may take quite a while for fuzzer to trim mutation list until no such exception throwing methods are left in it, especially without any feedback for exceptions thrown during value construction phase.

It seems like some improvements to fuzzer platform or some less direct solutions from our side are needed.

**Comment by IlyaMuravjov** [comment]
Replaced with #2344

**Comment by IlyaMuravjov** [comment]
Replaced with #2344
