### ISSUE TITLE
Investigate how to use fuzzing in Spring unit tests

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2321]
**Description**

We should finally investigate what to do with fuzzer in unit tests.

1. First of all, how can it be used in `No configuration` mode?
- May be for non-Spring classes (that do not inject mocks)
- May be for the items, that cannot be injected from Spring (e.g. collections passed to constructors)?

2. Investigate is it useful to generate unit tests with Fuzzing with Spring configuration applied
Substitute interfaces with implementations.
Seems that at least non-Spring classes (that do not inject mocks) Fuzzer may be useful in the mode with configuration too.
Investigate other cases to use Fuzzing with configuration.

3. There is a connected question how do we test some Utils class in Spring projects now, that injects nothing
- with engine?
- with fuzzer?

**Comment by IlyaMuravjov** [comment]
One not mentioned alternative, is to always use fuzzing in unit tests, and generate two (possibly nested) test classes:
  - test class with `@InjectMock` and engine generated tests;
  - test class without `@InjectMock` and fuzzer generated tests.

Furthermore, if either of these classes turns out to be empty we should skip it.

Finally, the only scenario when these two test classes can be merged into one seem to be when we have no `@Mock` fields.

**Comment by alisevych** [comment]
@IlyaMuravjov Please discuss possibility of mocking in Spring-specific-only Fuzzing
