### ISSUE TITLE
Fuzzer adds identical keys to Map in generated test

### ISSUE THREAD

**Issue by tyuldashev** [UnitTestBot/UTBotJava#2645]
**Description**
When Fuzzer generates tests data for `Map` it may add value by the same key twice.

**To Reproduce**

1. Install UnitTestBot plugin built from main in IntelliJ IDEA
2. Open UTBot Java project
3. Set Test generation method: Fuzzing = 100%
4. Generate tests for `examples.collections.Maps`

**Expected behavior**
Test doesn't contain adding identical keys to the Map.

**Actual behavior**
Some tests contain different values by identical keys.

**Screenshots, logs**

Sample of such test
~~~java
    @Test
    @DisplayName("mapOperator: map = collection")
    public void testMapOperator3() {
        Maps maps = new Maps();
        HashMap map = new HashMap();
        map.put("abc", "10");
        map.put("abc", "key");
    ...
~~~

**Environment**

IntelliJ IDEA version - 2023.2.2
Project - UTBot Java
JDK - 8

**Comment by Markoutte** [comment]
Fuzzer doesn't know about details of implementation, thus it is OK for it to generate same values in different places. For example, you can find an issue when same key (as a user can think) is added to the IdentityHashMap:

```
Map<Integer, String> m = new IdentityHashMap();
m.put(190190190, "one")
m.put(190190190, "two")
...
```

You can expect that the map contains 1 element in this case, but because of boxing primitive int value into Integer it doesn't happen and the map has 2 values inside. But you can find that this will work correctly for small integers like 1, 5 or another. It is because JVM contains preloaded Integer set for some range of primitive int set.

Same issue can be found when object of class with bad equals/hashCode is passed as a key.

So, now fuzzer works as intended.
