### ISSUE TITLE
Correct tooltips on popup in IDE

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#343]
**Description**

Hide/remove additional empty tooltip shown for every field except "Timeout for class".
Wording corrections for tooltips on IDEA popup. 

**Expected behavior**

1. Only one correct tooltip must be shown for every field on popup. 
Need to hide/remove additional empty tooltip.

*Wordings:*

2. Code generation language:
Now "Generating unit tests in Java"
Expected "Generate unit tests in Java"

3. Mock strategy:
Now "Do not use Mock frameworks at all"
Expected "Do not use mock frameworks at all"

4. Mock static:
Now "Don't use..."
Expected "Do not use..."

**Environment**

IntelliJ IDEA, Android studio

**Comment by JaneEugenia** [comment]
Code generation language:
Now "Generating unit tests in Java"
Expected "Generate unit tests in Java"  - **agree**

Mock strategy:
Now "Do not use Mock frameworks at all"
Expected "Do not use mock frameworks at all" - **agree**

As for Don`ts and do nots - if we want to make our UI more formal, it`s better to write tooltips without contractions. Otherwise, there is no big difference at all.

**Comment by korifey** [comment]
Dear @JaneEugenia @alisevych - for this kind of changes you can try to make PR by yourselves.
