### ISSUE TITLE
Class cast is missing for the instance of private nested class

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#731]
**Description**

Class cast is missing for the Object of private nested class.

**To Reproduce**

1. IntelliJ IDEA 2022.1.4 is running with UTBot plugin installed
2. Open a project with JDK 8/11
3. Add the following class to it:

```java
public class ABC {

    private class NML {
        public NML[] array = new NML[2];

        NML() {
            array[0] = null;
            array[1] = null;
        }
    }

    NML obj;

    ABC() {
        obj = new NML();
    }

    public int size() {
        return obj.array.length;
    }

}
```

4. Open the generated test

**Expected behavior**

Generated tests are supposed to be compilable.
Class cast must be added to the instance of the nested class, like 

```java
ABC.NML nml = ((ABC.NML) createInstance("ABC$NML"));
```

**Actual behavior**

Class cast is missing for the NML Object created by means of reflection.

**Visual proofs (screenshots, logs, images)**

The following test is present:

~~~java
public void testSize_ThrowNullPointerException_1() throws Exception  {
        ABC abc = new ABC();
        Object nml = createInstance("ABC$NML");
        setField(nml, "array", null);
        abc.obj = nml;
        
        /* This test fails because method [ABC.size] produces [java.lang.NullPointerException]
            ABC.size(ABC.java:19) */
        abc.size();
    }
~~~

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.1.4
JDK 8

**Additional context**

If private modifier is removed  - nested class is package-private or public - the class cast is made correctly.

**Comment by volivan239** [comment]
I believe you have forgotten `private` modifier in `class NML` declaration -- for the above code tests are generated correctly (at least, on my environment which differs only in IntelliJ version)

**Comment by alisevych** [comment]
> I believe you have forgotten `private` modifier in `class NML` declaration -- for the above code tests are generated correctly (at least, on my environment which differs only in IntelliJ version)

You're right! I've checked that **without private** modifier the class cast is made and forgot to put it back. Will correct.

**Comment by volivan239** [comment]
Nice! Still, I can't agree with expected behavior, the proposed solution gives me an `error: rndpkg.ABC.NML has private access in rndpkg.ABC`, because we can't declare anything of type `ABC.NML` outside of `ABC` (due to `private` modifier). So imo we need to declare it as `Object` and then use reflection for setting fields.

Just FYI, this code seems kind of weird to me: we have public field `obj` with class-private type, so outside of class `ABC` we can access the field, but we do not have any information about it's type. In Kotlin, e.g. this is restricted (translating this code to Kotlin in IDEA gives `[EXPOSED_PROPERTY_TYPE] 'public' property exposes its 'private' type NML` error in class declaration). See [this](https://www.reddit.com/r/Kotlin/comments/6ri0ao/comment/dl5a6ey/?utm_source=share&utm_medium=web2x&context=3) for more details. (But yes, in Java everything is legal, so we need to support this)

**Comment by alisevych** [comment]
@volivan239 Very useful, thanks a lot for explanations!

**Comment by alisevych** [comment]
@volivan239 Need to think of the common approach for such cases. Probably, it would be better not to generate a test like this. And inform the user about the inappropriate access modifiers combination. As an error comment in test class. 
@korifey , can you please advise?
